### PR TITLE
Implement `snap()` for single frame capture

### PR DESCRIPTION
**Pull request by BigRoy**
Implementation of `snap()` method for single frame capture. It defaults to format `image` and compression `png`. To keep functionality in sync with `capture()` it uses a direct call to capture.

#### Example

```python
import capture

# simple and quick
capture.snap()

# with viewport options saving an image of a specified frame with padding
view_opts = capture.ViewportOptions()
view_opts.nurbsCurves = True
view_opts.nurbsSurfaces = True
capture.snap(filename='D:/test_with_padding.png', 
             overwrite=True, 
             viewport_options=view_opts, 
             frame=5)

# with viewport options saving an image of a specified frame without padding (exact filename)
view_opts = capture.ViewportOptions()
view_opts.nurbsCurves = True
view_opts.nurbsSurfaces = True
capture.snap(complete_filename='D:/test_no_padding.png', 
             overwrite=True, 
             viewport_options=view_opts, 
             frame=5)
``

### CODE REVIEW

**Comment by mottosso** [comment]
The `complete_filename` argument, I haven't seen that keyword used anywhere, is it used elsewhere in Maya? It doesn't really speak for what it does. It seems `filename` is equally complete.

Would it be more intuitive to have a flag for padding?

```python
capture.snap(filename='D:/test_no_padding.png',
             padding=True,
             overwrite=True, 
             viewport_options=view_opts, 
             frame=5)
```

**Comment by BigRoy** [comment]
To me it's the worst naming as well. It's from the [playblast command](http://download.autodesk.com/us/maya/2011help/CommandsPython/playblast.html#flagcompleteFilename).

**Comment by mottosso** [comment]
Ah, okay, better keep it that then.

> Also note that the completeFilename argument makes FCheck function incorrectly.

To be honest, I wouldn't expect an image to open automatically following `snap`. If anything, it should open via the default image viewer of the OS, but that's difficult to determine in a cross-platform manner.

For now, I think it's perfectly safe to assume images are *not* opened automatically following a call to `snap`. In fact, I'd set `viewer=False` in `cmds.playblast` for `snap` explicitly.

**Comment by BigRoy** [comment]
Maybe set `viewer` to False by default for `snap()` but don't disable it. Doesn't the `maya.cmds.playblast` have an argument to override the default viewer being used?

Also I was thinking about the returned string from `snap`. When it contains padding in the name it returns the file name with #### in it. It would be better if it returned the exact name of the created frame since it'll always be one. What do you think?

**Comment by mottosso** [comment]
> Doesn't the maya.cmds.playblast have an argument to override the default viewer being used?

I think this is a Maya setting, under Preferences > Applications (bottom). Maybe set this temporarily? But the problem is still knowing which command to pass an image to. On Windows, it's possibly "start", but not so on other platforms.

> Maybe set viewer to False by default for snap() but don't disable it.

Yeah, sounds good too me.

**Comment by BigRoy** [comment]
What did you think of formatting the returned name so it contains the padded frame's name instead of ####?

Maybe set up an issue for customizing the viewer? Or is it outside of the scope of capture? With the filename teru

**Comment by mottosso** [comment]
> What did you think of formatting the returned name so it contains the padded frame's name instead of ####?

Could you give me an example output? I don't think I understand how you mean.

> Maybe set up an issue for customizing the viewer? Or is it outside of the scope of capture?

Yeah, why not. If capture is to replace `cmds.playblast`, it should probably cover the same responsibilities or more.

**Comment by BigRoy** [comment]
Currently it's like this:

```python
import capture

print capture.snap(filename='D:/test_awesome', overwrite=True, viewport_options=view_opts, frame=5)
# D:\test_awesome.####.png
```

**Comment by mottosso** [comment]
Ah, odd. Sure, I'd either strip those characters - `D:\test_awesome.png` - or replace them with the actual frame, - `D:\test_awesome.0020.png`.

**Comment by BigRoy** [comment]
Actually, we could also support this:

```python
capture.snap(frame=(1, 5, 9, 112))
```

This would capture only frame 1, 5, 9 and 112. What would we like returned in that scenario? Currently our `snap()` only supports capturing a single frame since it sets `start_frame` and `end_frame` for `capture()`. But we could also use `maya.cmds.playblast`'s `frame` argument.

**Comment by mottosso** [comment]
Haha, I like it, but why not just do this?

```python
for frame in (1, 5, 9, 112):
  capture.snap(frame)
```

**Comment by mottosso** [comment]
Let's use this to generate thumbnails with Magenta. :)

**Comment by BigRoy** [comment]
> for frame in (1, 5, 9, 112):
  capture.snap(frame)

That would trigger individual independent panels and playblast commands, whereas the other remains a single continuous stream. It's likely a lot faster doing it directly through the playblast command and not needing to set a viewport for each frame? I noticed getting the playblast command to run already takes a tiny bit at the moment.

**Comment by mottosso** [comment]
Hm, that's true, good call.

I'm worried it will obfuscate the implementation, and I'm not seeing a direct use-case for it. However, with such performance, we might be able to extend upon `snap()` to also capture arbitrary ranges, something I think is tricky otherwise (?).

For example.

```python
# psuedo
capture.snap(frame=[1, range(3, 12), 35, 100, range(200, 300)])
```

Still not fully convinced the use-cases fully justify the added complexity though..

**Comment by BigRoy** [comment]
>  # psuedo
capture.snap(frame=[1, range(3, 12), 35, 100, range(200, 300)])

Should work fine if we just flatten the input list?

**Comment by BigRoy** [comment]
By the way, I think we should do it this way.

`snap()` is always a single frame, no matter what. This makes `snap()` just a simple helper function to quickly snap a single frame.

Then we just allow the `frame` argument for `capture()` so we can capture arbitrary frames and sequences?

**Comment by mottosso** [comment]
> Then we just allow the frame argument for capture() so we can capture arbitrary frames and sequences?

Sounds much more expected, yes, let's try that.

**Comment by BigRoy** [comment]
There we go. This works now:
```python

frames = [1, 5, range(10, 30), [50, 60, 70]]
capture.capture(frame=frames)
```

Note that it will name any sequence (if using format 'image' for example) starting at zero. 

So now we can do:

```python
frames = [1, 5, range(10, 30), [50, 60, 70]]
capture.capture(frame=frames, filename='D:/test.png', format='image', compression='png', raw_frame_numbers=True)
```

This will give a warning message that `viewer` is disabled (set to False). Because `maya.cmds.playblast` can't have viewer enabled together with raw frame numbers. To avoid that warning:

```python
frames = [1, 5, range(10, 30), [50, 60, 70]]
capture.capture(frame=frames, filename='D:/test.png', format='image', compression='png', raw_frame_numbers=True, viewer=False)
```

**Comment by mottosso** [comment]
Oh, sorry, I didn't mean for that to be the actual syntax, I think it might be a bit too convoluted.

```python
frames = [1, 5, range(10, 30), [50, 60, 70]]
```

I was attempting to create a single list of integers, using `xrange` as a helper.

```python
frames = [1, 5, 10, 11, 12, 13, 14, 15, 50, 60, 70]
```

I think this might be how I was thinking.

```python
frames = [1, 5] + range(10, 30) + [50, 60, 70]
```

To keep things simple and generic. :S What do you think?

**Comment by BigRoy** [comment]
> To keep things simple and generic. :S What do you think?

Yes, both is fine for me. All that would have to be removed is *flattening the list*. At this moment it supports both. I think we can drop support for the nested one since it's trivial to flatten the list outside of the capture() command. Also a single frame is still supported in both ways: `capture(frame=5)`.

---

Something we haven't had much of a look at is playblasting sub-frames. The command works fine if you do `capture(frame=0.25)` for example. This also works fine to video:

```python

# time remapped
start = 1
end = 100
speed = 0.5     # could also be named 'step'
num_frames = int(float(end-start) / speed) + 1
print num_frames
frames = range(num_frames)
frames = [start + (x*speed) for x in frames]

capture.capture(frame=frames)
```

Even works fine to an image format (it will number from 0000), until you do `raw_frame_numbers=True`. Because it will save out the images' frames to rounded numbers.

**Comment by BigRoy** [comment]
With the *nested frame ranges* support now dropped for `capture(frame)` and having `snap()` only *snap a single image* I feel confident this is ready to merge.

All I quickly found was a typo in the docstring (*and* should be *an* before *error*):

```python
...
"""
overwrite (bool, optional): Whether or not to overwrite if file
            already exists. If disabled and file exists and error will be
            raised.
"""
...
```

**Comment by mottosso** [comment]
Ok, having a closer look

**Comment by mottosso** [comment]
> Seems like it becomes time to get test-driven?

That would be ideal, but I can't think of how to properly do that.

There are two major obstacles; (1) tests need Maya, which makes it difficult to automate via something like Travis, and (2) the end results depend on the GUI - the isolated panel. To properly test it, we would need to run Maya with a GUI, and then depend on a new window appearing. Both of which are real tricky to automate safely..

To make it testable, we will need to strip away the GUI portion from `capture()` such that we can test everything that *isn't* using the GUI, like the flags and outputted images. The tests could still to off-screen capturing, and the flags and options are still important to test.

**Comment by mottosso** [comment]
About this PR, I think it looks great. Merging, but let's keep the discussion about it going in here for completeness.

**Comment by BigRoy** [comment]
> There are two major obstacles; (1) tests need Maya, which makes it difficult to automate via something like Travis, and (2) the end results depend on the GUI - the isolated panel. To properly test it, we would need to run Maya with a GUI, and then depend on a new window appearing. Both of which are real tricky to automate safely..

> To make it testable, we will need to strip away the GUI portion from capture() such that we can test everything that isn't using the GUI, like the flags and outputted images. The tests could still to off-screen capturing, and the flags and options are still important to test.

Completely true. Though even running Maya and performing a test of the package manually could capture a lot of issues down the line, especially with pull requests coming in.

Either way it would be great to have a look into how we can set up tests for the package.

**Comment by BigRoy** [comment]
Oops, just found a bug! 
I'm getting this:

```python
import capture

capture.snap(filename='test')
# Error: Invalid arguments for flag 'frame'.  Expected time, got NoneType
# Traceback (most recent call last):
#   File "<maya console>", line 9, in <module>
#   File "E:\Projects\maya-capture\capture.py", line 161, in snap
#     output = capture(*args, **kwargs)
#   File "E:\Projects\maya-capture\capture.py", line 125, in capture
#     **playblast_kwargs)
# TypeError: Invalid arguments for flag 'frame'.  Expected time, got NoneType # 
```

Squashing it now.

**Comment by mottosso** [comment]
No problem.

Another good reason for tests.

**Comment by BigRoy** [comment]
Got it. Also found an annoying warning coming from `snap` if not used with `frame` argument.

```
# Error: -rawFrameNumber option must be used with at least one -frame flag, ignoring -rawFrameNumber. # 
```

Will capture that one as well, and set up a fix pull request.

**Pull request merged**
