### PR TITLE
Add more options

### PR DESCRIPTION
**Pull request by BigRoy**
- Include Viewport 2.0 settings #1 
- Include more ViewportOptions that use `modelEditor` as command.

### CODE REVIEW

**Comment by mottosso** [comment]
Tiny tiny nitpick, but it'll drive someone crazy at some point; could you put the two viewport_options and viewport2_options right next to each other in the argument list? :)

**Comment by BigRoy** [comment]
To be really nitpicky... before or after `display_options`?

**Comment by mottosso** [comment]
You pick :)

**Comment by BigRoy** [comment]
Like that?

**Comment by mottosso** [comment]
Yeah, looks good to me. What do you think?

**Comment by BigRoy** [comment]
Yes, looks clean.

**Pull request merged**
