### PR TITLE
Implement `apply_view` and `applied_view`

### PR DESCRIPTION
**Pull request by BigRoy**
Implement the function and context manager to easily apply parsed options with the `parse_view` command.

```python
import capture

# Parsing options
options = capture.parse_view("modelPanel1", "top")

# Applying options
capture.apply_view("modelPanel1", "persp", **options)

# Context manager
with capture.applied_view("modelPanel1", "persp", **options):
    pass
```

This only adds the function and does not yet swap it out in the `capture()` method as a replacement to the separate `_applied_*_options*` functions.

### CODE REVIEW

**Comment by mottosso** [comment]
Looks great, and good work on adding tests. There are a few more tests I think we should make before merging.

Now that we can both parse and apply a view, we can try them against each other, which means we are able to reach 100% test coverage and guarantee bug free code. A rare opportunity, making the feature worth implementing, even if we would have made it for pure internal reasons.

The result of applying a view, should result in an identical parse of the same view. Similarly, the parse of a view should result in an identical apply. We can test applied settings using the normal `cmds` module, and the parse module by simply comparing the two dictionaries.

```python
# psuedo
cmds.viewport(showWireframe=True)
assert parse_view()["showWireframe"] is True

# important to test both, just in case wireframe was already
# True when making the first query, and to make sure this
# actually does something.
cmds.viewport(showWireframe=False)
assert parse_view()["showWireframe"] is False

apply_view({"showWireframe": True})
assert cmds.viewport(showWireframe=True, query=True) is True
```

See if you can make a test or two that absolutely proves that each aspect of `apply` works, and has absolutely no bugs.

**Comment by BigRoy** [comment]
Thanks for the pseudocode, in reality it's a bit more extensive since the information is nested in the options dicts. See my commit. Could probably be written a bit cleaner when brain had some coffee. So far this runs and tests ok!

**Comment by mottosso** [comment]
Sweeeet!

Do you think this could be made as a loop through all available options in ViewportOptions, ViewportOptions2, CameraOptions and DisplayOptions? Where `parse` tests every aspect of `view` and vice versa? That way, we would achieve 100% coverage and fully bug free code!

**Comment by BigRoy** [comment]
It could be a loop but for many options it's hard to automate what both sides of a value could be. For example the one that's there now toggles `smoothShaded` to `wireframe` as a string.

What could be done is add a complete set op options like those defaults in `capture.py` where every single key, value is set another value. In that case it'd be roughly the size (lines of code) as the dictionaries in `capture.py`.

At the same time any "setting" or "getting" of values would become a similar implementation (to iterate through the options and apply) as in `apply_view`. As such any bugs in that method would both be present in that implementation as it is in the test.

To get better coverage without getting to much lines of code is just getting 2 dictionaries of options (two differing states) that cover most (could be all, but is long) settings and differ a lot between the two states.

Maybe the test should just be loading two .json files as presets (`state1.json` and `state2.json`) then the result could be checked whether after applying when parsed it contains the options of those states.

What do you think?

**Comment by mottosso** [comment]
From experience, I would avoid external data files, they can cause issues when run on various platforms and especially cloud-hosted ones such as Travis.

There's no reason you couldn't make `state1.py` and simply put a dictionary there, but I would probably vouch for a dictionary directly in the test function. It can get long, but that's ok, so long as it's clear.

**Comment by BigRoy** [comment]
Cool, sounds reasonable. 

Hope to find some time on my hands later today to have a look. Otherwise it's going to be one of my "morning coding" things as I wake up tomorrow. ;)

**Comment by mottosso** [comment]
> Hope to find some time on my hands later today to have a look. Otherwise it's going to be one of my "morning coding" things as I wake up tomorrow. ;)

No problem, take your time.

This is shaping up to be the most solid little Maya helper script ever. :)

**Comment by BigRoy** [comment]
And there is one monster of a test. Preferrably I'd have it throw assertion errors for each wrong value so it's easier to debug. Now it just fails the test if any of the values parsed are different from what was being set.

Even though it's big it should be pretty clear code.

**Comment by mottosso** [comment]
Looks good. :)

We can polish it as time goes by. The goal is for it to constrain the essence of the library that shouldn't change, while allowing us to add and adjust new or surrounding features. Right now, it might be a bit too restrictive, but the best way to find out I think is by taking it for a spin.

Great work!

**Pull request merged**
