### PR TITLE
Parse (active) view

### PR DESCRIPTION
**Pull request by BigRoy**
Parse the active view so they can also be used as options.

```python
import capture

options = capture.parse_active_view()
capture.capture(**options)
```

Technical artists can also specify a specific camera and panel using `capture.parse_view(panel, camera)`.

### CODE REVIEW

**Comment by mottosso** [comment]
So clean, thanks Roy. Have you tested it, it works and all? Could you add a few tests to tests.py?

**Comment by BigRoy** [comment]
Have tested it manually. Will commit tests in a bit.

**Comment by BigRoy** [comment]
Tests are added.

**Comment by mottosso** [comment]
Great work; we'll be able to add a bunch of more tests, once the `apply_view` is implemented as well. They should take each other out 1-1.

**Pull request merged**
